Fix building in C++11 mode with Clang
This fixes building with Clang 6.0, which defaults to C++14, that
previously errored out due to errors like these:

src/main.cpp:857:73: error: invalid suffix on literal; C++11 requires a space
      between literal and identifier [-Wreserved-user-defined-literal]
        DISPATCHER_LOG_ERROR((("MFXAudioUSER_UnLoad : plugin with GUID="MFXGUIDT...

Even if GCC 6 also defaults to C++14, the same issue is only a
warning there, not an error.